### ISSUE TITLE
Extract logic from CLI

### ISSUE THREAD

**Issue by robinandeer** [moonso/loqusdb#2]
I would really like to use the Python API to load variants but it seems that there's a lot of logic in the CLI which makes it difficult unless a rewrite a lot of what's already there

Would you be against pulling out logic from the CLI and exposing it in the API? Or would you rather prefer I write my own bindings to the CLI and call it with `subprocess`?

**Comment by moonso** [comment]
No I agree, will try to move in the direction that you suggest
