### ISSUE TITLE
same family added twice? :/

### ISSUE THREAD

**Issue by robinandeer** [moonso/loqusdb#20]
Hi,

I'm pretty sure I loaded a family from an empty database.

However many variants seem to be linked to the same case/family multiple times

<img width="485" alt="screen shot 2016-11-25 at 08 02 11" src="https://cloud.githubusercontent.com/assets/1220232/20616884/c2b79524-b2e5-11e6-94d5-3a93afab31ae.png">

What do you need to debug this? I can provide the WGS VCF on rasta.

Perhaps you can just check if the family is already in the array before appending another one?

I will rerun the loading after dropping the collections to make sure I can reproduce this...

**Comment by robinandeer** [comment]
Just one case is added so I guess that means I haven't loading the VCF twice, right?

**Comment by moonso** [comment]
Could you show how the case collection looks like?

**Comment by moonso** [comment]
Ok so we have located the problem, there where multiple versions of the exact variant in the VCF.
I will implement a check so that this will not be allowed in loqusdb.
