### ISSUE TITLE
avoid logging password

### ISSUE THREAD

**Issue by robinandeer** [moonso/loqusdb#23]
I noticed that loqusdb log the password used to connect to the database in clear text to the terminal - this probably isn't best practise (although I'm sure Chanjo probably does the same...)

Perhaps replace that section with `****`, like:

```
[2017-02-16 14:36:30,476] INFO : loqusdb.plugins.mongo.adapter : Connecting with uri mongodb://writer:********@localhost:27019/loqusdb
```

**Comment by moonso** [comment]
hehe you are right of course, will fix!
