### ISSUE TITLE
Sort positions when storing/querying bnd

### ISSUE THREAD

**Issue by J35P312** [moonso/loqusdb#37]
Hello there!
I have a bunch of variant callers that sometimes represent the same BND in different way. For example this stranslocation:

chr1 10000, chr2 50000

is sometimes called like this:

chr2 50000, chr1 10000

(depending on calling, filtering etc)
Maybe we could add some sort by contig function to loqus to make sure that we always get the same result when searching for the same BND? 

Regards
//JEsper

**Comment by moonso** [comment]
Yes that sounds intelligent, always lowest chromosome number and chromosome position first.
I'll work on that.

**Comment by moonso** [comment]
Ok this should be fixed if you update

**Comment by J35P312** [comment]
That's really nice! Thanks a lot!
