### ISSUE TITLE
--end-chromosome is not used

### ISSUE THREAD

**Issue by J35P312** [moonso/loqusdb#39]
Hello!
I searched for an interchromosomal translocation stored in a loqusdb sv database.
It could not be found, looking at the search, it seems that the --end-chromosome parameter is not used, instead the end_chrom is set  to --chrom

![interchromosomal_tra](https://user-images.githubusercontent.com/12830429/41341764-d004ae42-6efa-11e8-8470-1e0248812ef2.png)

**Comment by moonso** [comment]
Fixed!
