### ISSUE TITLE
release 1.0 logs wrong connection string

### ISSUE THREAD

**Issue by ingkebil** [moonso/loqusdb#42]
https://github.com/moonso/loqusdb/blob/6b34e919ec0e7eee8f4f7fb1d91492a3501670df/loqusdb/plugins/mongo/adapter.py#L30

Will log the default port and host even when an `uri` is given. This may lead to confusion when not connecting to either of those.

Proposed solution: log based on a given `uri`.

**Comment by ingkebil** [comment]
Possible solution here: https://github.com/ingkebil/loqusdb/blob/log_uri/loqusdb/plugins/mongo/adapter.py

**Comment by moonso** [comment]
Will solve this with http://api.mongodb.com/python/current/api/pymongo/uri_parser.html

**Comment by moonso** [comment]
Fixed in version 2.0!
